### ISSUE TITLE
Broken with Python 2.6

### ISSUE THREAD

**Issue by frostynova** [bibby/radula#5]
```
Traceback (most recent call last):
  File "/usr/bin/radula", line 7, in <module>
    from radula import main
  File "/usr/lib/python2.6/site-packages/radula/__init__.py", line 5, in <module>
    from rad import Radula, RadulaError, RadulaClient, config_check
  File "/usr/lib/python2.6/site-packages/radula/rad.py", line 823
    return {k: v for k, v in subject.metadata.items() if k in RadulaHeaders.values()}
                   ^
SyntaxError: invalid syntax
```

**Comment by bibby** [comment]
Thanks for this report. There could be _lots_ of things that don't work with python 2.6, but my largest concern is around the external dependencies; so it's hard to say if fixes can be permanent.

For us, we install radula in a [virtualenv](https://pypi.python.org/pypi/virtualenv) and link `bin/radula` to `/usr/local/bin/` so that it runs with python 2.7 (as 2.6 is the default on some of our hosts).

**Comment by bibby** [comment]
The test suite still doesn't run under python 2.6, but I tried out most of the commands and yours was the only problem I encountered.
