### ISSUE TITLE
Ommit existant files

### ISSUE THREAD

**Issue by adrianlzt** [bibby/radula#9]
If the upload fails with half of the files, for example, because it "hits" with a directory, the upload should be started again from the beginning, using -f because some of the files are already in the bucket.

An option to ignore files already in the bucket will fix this problem.

**Comment by bibby** [comment]
I think I get it. Currently, if the remote file exists, an error is given refusing to overwrite.
Using `radula -f`, the remote file is rewritten.
The request is to add a flag to *happily* not overwrite, instead of *angrily* refuse.

**Comment by bibby** [comment]
A new flag `-i,--ignore-existing` has been added to the dev branch, and applies to uploads and downloads. Rather than exit with an error, an INFO level message is printing stating that the procedure for that key has been skipped. No consideration is yet given towards the difference in file content or modification times; they are skipped simply for existing.

This should hopefully not interrupt any loops you might be doing, and it plays nicely with the recursive up/down features that were added as well, in response to #8 . I'll try to explain there why a merge is not happening immediately.
